#ifndef SSGI_TYPES_HLSL
#define SSGI_TYPES_HLSL

#define RAYMARCHINGFALLBACKHIERARCHY_NONE                  0
#define RAYMARCHINGFALLBACKHIERARCHY_SKY                   1
#define RAYMARCHINGFALLBACKHIERARCHY_REFLECTION_PROBES     2
#define RAYMARCHINGFALLBACKHIERARCHY_REFLECTION_PROBES_AND_SKY 3

#endif // SSGI_TYPES_HLSL
